### ISSUE TITLE
Inquiry: Project Status Regarding DuCoWallet

### ISSUE THREAD

**Issue by Tech1k** [viktor02/DuCoWallet#2]
Hello @viktor02 ,

I am Kristian, the webmaster and site maintainer for Duino-Coin. I am reaching out to inquire about the current status and compatibility of the DuCoWallet project as it is listed on our verified apps page (https://duinocoin.com/apps).

Could you please provide me an update regarding the project's status when you have time?

Thank you for your cooperation.

Sincerely,
Kristian

**Comment by viktor02** [comment]
Looks like the api has changed and the wallet doesn't work after that. I have no reason to continue developing my wallet

**Comment by Tech1k** [comment]
Thank you for the swift reply and for letting me know about this. If you ever decide to resume development on your wallet, feel free to let me know and I'll re-add DuCoWallet onto the verified apps page.
